import {
  IconBrandLinkedinFilled,
  IconBrandGithub,
  IconBrandReact,
  IconMailFilled,
  IconWorld,
  IconBrandNextjs,
  IconBrandTypescript,
  IconBrandRedux,
  IconBrandTailwind,
  IconBrandHtml5,
  IconBrandCss3,
  IconBrandJavascript,
  IconBrandGit,
  IconBrandVscode,
  IconDirectionsFilled,
  IconBrandVercelFilled,
  IconBrandFiverr,
  IconBrandUpwork,
  IconFlaskFilled,
} from "@tabler/icons-react";

const LinkedInIcon = IconBrandLinkedinFilled,
  GithubIcon = IconBrandGithub,
  ReactIcon = IconBrandReact,
  EmailIcon = IconMailFilled,
  GlobeIcon = IconWorld,
  TypeScriptIcon = IconBrandTypescript,
  ReduxIcon = IconBrandRedux,
  TailwindCSSIcon = IconBrandTailwind,
  HTMLIcon = IconBrandHtml5,
  CSSIcon = IconBrandCss3,
  JavascriptIcon = IconBrandJavascript,
  GitIcon = IconBrandGit,
  VSCodeIcon = IconBrandVscode,
  RestAPIIcon = IconDirectionsFilled,
  VercelIcon = IconBrandVercelFilled,
  UpworkIcon = IconBrandUpwork,
  FiverrIcon = IconBrandFiverr,
  VitestIcon = IconFlaskFilled,
  NextJsIcon = IconBrandNextjs;

export {
  LinkedInIcon,
  GithubIcon,
  ReactIcon,
  VitestIcon,
  EmailIcon,
  GlobeIcon,
  NextJsIcon,
  TypeScriptIcon,
  ReduxIcon,
  TailwindCSSIcon,
  HTMLIcon,
  CSSIcon,
  JavascriptIcon,
  GitIcon,
  VercelIcon,
  VSCodeIcon,
  UpworkIcon,
  FiverrIcon,
  RestAPIIcon,
};
